config/routes.rb
Rails.application.routes.draw do
  devise_for :superusers
  root to: 'events#index'
  get 'abouts/show' => "abouts#show"
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

    has_many :superusers # moderators

    # Generate special links to events
    extend FriendlyId
    friendly_id :title, use: :slugged

    # Sort the 'events'
    scope :most_recent, -> {order(id: :desc)}

    # User inputs validation
    validates :title, presence: true
    validates :description, presence: true
    validates :body, presence: true
    validates :local, presence: true
    validates :day, presence: true
    validates :organization, presence: true

    # Update the link if it is necessary
    def should_generate_new_friendly_id?
        title_changed?
    end

end

app/models/superuser.rb
class Superuser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :events
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_superuser!, only: [:edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.most_recent.paginate(page: params[:page], per_page: 6)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :body, :local, :day, :organization, :image_url)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/abouts/show.html.erb
<!--Este arquivo é referente à página "Sobre"-->

<div class="container">
	<div class="row">
            <div class="row">
                <div class="col-md-4 text-center">
                    <div class="box">
                        <div class="box-content">
                            <h1 class="tag-title">O que fazemos?</h1>
                            <hr />
                            <p class="text-justify">Somos um site que vem com o proposito de promover eventos artistícos e de entretenimento em geral, como rodas de dança, exposições de artes e fotografia, competições de jogos online, entre outros. Sabemos que o consumo de arte em geral é bastante importante, e gostariamos de manter esse consumo e promover o mesmo para que a população brasileira possa ter acesso a informação da cultura de uma forma mais fácil e simples.</p>
                            <br />
                        </div>
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <div class="box">
                        <div class="box-content">
                            <h1 class="tag-title">Como fazemos?</h1>
                            <hr />
                            <p class="text-justify">Estamos trabalhando nessa plataforma para que as pessoas possam divulgar tais exposições e encontros de forma que todos possam ter acesso à aquilo que mais gostam. Sabemos também que muitos não conhecem eventos artísticos daquilo que se tem mais interesse e gostariamos de dar mais acessibilidade e informação para que todos possam curtir e aproveitar a vida de uma forma mais divertida.</p>
                            <br />
                        </div>
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <div class="box">
                        <div class="box-content">
                            <h1 class="tag-title">Quem somos?</h1>
                            <hr />
                            <p class="text-justify">Somos os estudantes Dâmaso Júnio e Welison Almeida do 3º semestre de Engenharia de Software da UnB-Gama. E esse projeto faz parte de um trabalho proposto pela disciplina de Orientação à Objetos pelo Professor Renato Sampaio.</p>
                            <br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
	<hr/>
	<footer>
        <p>&copy; 2018 FindEvent, Inc.</p>
      </footer>
</div>

app/views/events/_event.html.erb
<!--Este arquivo é responsável pela criação dos cards de eventos na Paǵina Principal-->
<div class='col-sm-6 col-lg-4'>
    <div class="card">
        <div class="card-topper" style='background-image: url(<%= event.image_url %>);'></div>
        <div class="card-block">
            <h4 class="card-title"><%= link_to event.title, event %></h4>
            <p class="published-date"><%= truncate(event.local, length:130) %></p>
            <p class="published-date"><%= event.day %></p>
            <p class="card-text"><%= truncate(event.description, length:130) %></p>
            <%= link_to 'Info', event, class: 'btn btn-read'%>
        </div>
    </div>
</div>

app/views/events/_form.html.erb
<!--Este arquivo é responsável pela pagina de Criação de Eventos-->
<div class="blocktext-create-event">

    <%= form_with(model: event, local: true) do |form| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.text_field :title, placeholder: 'Título', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.text_field :description, placeholder: 'Descrição', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.text_field :image_url, placeholder: 'Imagem URL', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.text_field :local, placeholder: 'Local', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.text_field :day, placeholder: 'Data (AAAA-MM-DD HH:MM:SS)', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.text_field :organization, placeholder: 'Organização', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.text_area :body, placeholder: 'Informações', class: 'form-control' %>
      </div>
      <div class="blocktext-login">
        <div class="form-group">
          <%= form.submit "Confirmar", class: "btn btn-primary btn-block btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>

app/views/events/edit.html.erb
<!--Este arquivo é referente à pagina de edição de eventos pelo SuperUser-->
<% provide(:page_title, "Editar #{@event.title}")%>

<div class="blocktext">
    <h1 class="text-center">Editar Evento</h1>
    <hr>
</div>

<%= render 'form', event: @event %>

<div class="blocktext-login">

  <%= link_to 'Mostrar', @event, class: "btn btn-primary btn-block btn-lg"  %>
  <%= link_to 'Voltar', events_path, class: "btn btn-primary btn-block btn-lg"  %>
</div>

app/views/events/index.html.erb
<% provide(:page_title, 'Todos os eventos')%>

<!--Referente a renderização da parcial "_event" -->
<div class="row">
  <%= render @events %>
</div>

<%# Personalize the WillPaginate default pagination %>
<%= will_paginate @events, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, previous_label: "Anterior", next_label: "Próximo", inner_window: 2 %>

app/views/events/new.html.erb
<!--Este arquivo chama o arquivo "form" que é responsável pela criação de novos eventos-->
<% provide(:page_title, 'Novo evento')%>

<div class="blocktext">
    <h1 class="text-center">Novo Evento</h1>
    <hr>
</div>

<%= render 'form', event: @event %>

<div class="blocktext-login">

<%= link_to 'Voltar', events_path, class: "btn btn-primary btn-block btn-lg"  %>

</div>

app/views/events/show.html.erb
<!--Este arquivo é responsável por montar toda a página "Info" de cada evento.-->
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<% provide(:page_title, @event.title)%>

<div class="container">
    <div class="well">
        <div class="row">
             <div class="col-md-12">
                 <div class="row hidden-md hidden-lg"><h1 class="text-center" ><%= @event.title %></h1></div>
                 <div class="pull-left col-md-4 col-xs-12 thumb-contenido">
                   <img class="center-block img-responsive container" src='<%= @event.image_url %>'/>
                 </div>
                 <div class="">
                     <h1 class="hidden-xs hidden-sm"><%= @event.title %></h1>
                     <h3 class="hidden-xs hidden-sm"><%= @event.description %></h3>
                     <hr>

                     <p><strong>Data: </strong><%= @event.day %><br>
                       <br>
                     <strong>Organização: </strong><%= @event.organization %><br>
                       <br>
                     <strong>Local: </strong><%= @event.local %></p>
                     <hr>

                    <p class="text-justify">
                      <%= @event.body %>
                    </p>
             </div>
        </div>
    </div>
    <% if superuser_signed_in? %>
    <div class="row">
      <div class="col-lg-2">
        <div class="blocktext-show">
          <%= link_to 'Voltar', events_path, class: "btn btn-primary btn-block btn-xs"  %>
        </div>
      </div>
      <div class="col-lg-2">
        <div class="blocktext-show">
          <%= link_to 'Editar', edit_event_path(@event), class: "btn btn-primary btn-block btn-xs"  %>
        </div>
      </div>
      <div class="col-lg-2">
        <div class="blocktext-show">
          <%= link_to 'Deletar', event_path(@event), method: :delete, class: "btn btn-danger btn-block btn-xs" %>
        </div>
      </div>
    </div>
    <% else %>
    <div class="row">
      <div class="col-lg-4">
        <div class="blocktext-show">
          <%= link_to 'Voltar', events_path, class: "btn btn-primary btn-block btn-xs"  %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!--Este arquivo é responsável pela barra de navegação, que é renderizada em todas as páginas do website-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">FindEvent</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Sobre", abouts_show_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Criar evento", new_event_path %></a>
      </li>
      <%if superuser_signed_in?%>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Sair",  destroy_superuser_session_path, method: :delete %> </a>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Área restrita",  new_superuser_session_path %> </a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!-- Este arquivo é responsável pela execução de HTMLs em toda a estrutura do site, é principalmente usado para renderizar a NavBar -->
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> - FindEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>